# .cargo/config

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
     "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes" 
     # 设置链接脚本以及强制打开 fp 选项，这样才会避免 fp 相关指令被编译器优化掉。
]
